name: Update customized gist

on:
  push:
    branches:
      - main
    paths:
      - customized/index.ts
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.gist.outputs.url }}
    steps:
      - uses: actions/checkout@v5
      - name: Update gist from file
        id: gist
        uses: xSAVIKx/gist-uploader-action@v0.1.3       # pin to a released version
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 9c9b2a0b0e6857bc5ecc1665e095d963     # ID of the target gist
          file_path: customized/index.ts  # path in your repo to upload
          gist_description: "GCP Cloud Workstations customizable setup with Pulumi, Typescript and Bun"
          gist_file_name: index.ts
